### ISSUE TITLE
Not Compatible with GigDigit MPSM 'Quiet' Mainboard 

### ISSUE THREAD

**Issue by RAMilewski** [bruhmann/OctoPrint-EEPROM-MPSelectMini#7] opened 2020-03-28 22:31 UTC
GigDigit has released a "Quiet" version of the mainboard for the MPSelectMini.
I recently replaced the mainboard in my MPSM V1 and it does provide a remarkable reduction in motor noise.  Sadly, however, this Octoprint plugin no longer works with my machine.  I'm sending GigDigit a note about this issue in hopes of them providing the necessary information for you to provide a revision that works with their board.

**Comment by RAMilewski** [comment] 2020-03-30 01:14
It appears that the issue may be that the "quiet" boards are running Marlin 2.0.   Is the plug-in otherwise compatible with Marlin 2.0?

**Comment by bruhmann** [comment] 2020-03-30 12:21
Does it just give a warning?  Are you blocked from using the plugin at all?

I can work on unblocking you, but I have no way to test the plugin or guarantee that everything will work properly.  Knowing what you're seeing will help me understand where you might be getting blocked.

**Comment by RAMilewski** [comment] 2020-03-30 23:37
Just the message: 

> Sorry, This plugin is not compatible with your machine. It has only been tested with Malyan based firmware for the Malyan M200 and the Monoprice Select Mini. 

The design engineer at GigDigit said he has looked at the code and thinks he understands why.  He's setting up an OctoPi to test, so with luck you should be getting a PR here soon.   I'll encourage him to check in on this thread so you can trade information.

**Comment by mhervieux** [comment] 2020-05-27 21:43
Just checking if there has been an update to this. I've just loaded my first install of OctoPrint and couldn't get it to work (Error: Failed to autodetect serial port, please set it manually) and since I also have a Gigdigit (M200_V1-V2-MAINBOARD-QUIET-F401) this compatibility could be the problem.  If there is anything that I can do to help test and debug, please let me know.,

**Comment by MatthewUpp** [comment] 2020-05-31 14:29
Please try installing and testing this - [OctoPrint-EEPROM-Malyan-STM32F401](https://github.com/MatthewUpp/OctoPrint-EEPROM-Malyan-STM32F401)

I'll add M851, M907, and maybe a couple more if I find some are missing.

This has not been tested other than connecting different boards and printers to see if the fields are populated with the EEPROM info.

**Comment by mhervieux** [comment] 2020-06-01 18:22
Just tried installing the plugin and while it installed without error, I continue to not be able to recognize the serial port to connect.  The error I get is "There was an unknown error while talking to your printer. Please consult the terminal output and octoprint.log for details. Error: Failed to autodetect serial port, please set it manually."  The serial port's only option is "Auto" but I've tried each of the baud settings, a few different cables, different USB ports and all of the baud rates just to sure.  Still nothing.  The only additional info in the log is "Serial port list: []."  Any direction on how to set the serial port explicitly?  I thought that for this printer "auto" is the only option.

**Comment by MatthewUpp** [comment] 2020-06-02 01:14
@mhervieux I'll email about your problem. If "Auto" is your only option then something else is going on unrelated to this or the other plugin.

**Comment by MatthewUpp** [comment] 2020-06-02 01:22
@bruhmann I feel you can close this issue. The issue is not really a problem with your fork of the plugin.
I'll do a little more testing with different firmware versions and different model printers that I believe it should work with and then register it to be added to the OctoPrint plugin repository.

**Comment by bruhmann** [comment] 2020-07-18 02:21
Thank you @MatthewUpp , I appreciate the help.

**Closed as completed by bruhmann** 2020-07-18 02:21 UTC
